---
letsencryptnginx_acme_directory_url: https://acme-staging-v02.api.letsencrypt.org/directory
letsencryptnginx_acme_version: 2
letsencryptnginx_csr_country: CA
letsencryptnginx_docker_extra_volumes: []
letsencryptnginx_docker_image: nginx:stable
letsencryptnginx_docker_required_volumes:
  config: /var/docker-volumes/nginx/config
  localtime: /etc/localtime
  www: /var/docker-volumes/nginx/www
letsencryptnginx_key_size: 4096
letsencryptnginx_key_type: RSA
letsencryptnginx_maintainer: "Ansible managed"
letsencryptnginx_remaining_days: 30
letsencryptnginx_selfsigned_days: 365
letsencryptnginx_websites: []
