---
- name: Configure Google Antigravity Repository
  block:
    - name: Ensure keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Remove old Antigravity GPG key if exists
      ansible.builtin.file:
        path: /etc/apt/keyrings/antigravity-repo-key.gpg
        state: absent

    - name: Download and install Google Antigravity GPG key
      ansible.builtin.shell:
        cmd: curl -fsSL https://us-central1-apt.pkg.dev/doc/repo-signing-key.gpg | gpg --dearmor --yes -o /etc/apt/keyrings/antigravity-repo-key.gpg
        creates: /etc/apt/keyrings/antigravity-repo-key.gpg

    - name: Add Google Antigravity repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={% if ansible_architecture == 'x86_64' %}amd64{% else %}{{ansible_architecture}}{% endif %} signed-by=/etc/apt/keyrings/antigravity-repo-key.gpg] https://us-central1-apt.pkg.dev/projects/antigravity-auto-updater-dev/ antigravity-debian main"
        state: present
        update_cache: true
  become: true

- name: Install Google Antigravity
  apt:
    name:
      - antigravity
    state: latest
    install_recommends: false
    update_cache: true
  become: true
